### PR TITLE
Fix typo in docs.

### PR DESCRIPTION
**Pull request by cyphase**
There is only one Burrow.

### CODE REVIEW

**Comment by jcrist** [comment]
Thanks!

**Comment by cyphase** [comment]
Thanks for merging!

I happened to notice that my name in the commit was replaced with my name on GitHub ("Cyphase"). If it's not too much trouble, could you fix that? Force-pushing makes my eye twitch, but since I caught it quickly and I'm the only GitHub-tracked fork, I figured it wouldn't hurt to ask.

**Comment by jcrist** [comment]
Sure, should be updated.

**Comment by cyphase** [comment]
Thanks, I appreciate it.

**Pull request merged**
